### ISSUE TITLE
Road Map(v2)

### ISSUE THREAD

**Issue by TIMMLOPK** [TIMMLOPK/genshin-kit.js#2]
# 1. Better DX
- [x] use login to replace `setltoken` and `setltuid`
- [x] cookie , language ... in the object instead of many parameter
- [x] use `zod` to check input
- [x] Rename some methods 

# 2. Feature 
- [x] Get cookie from browser 
- [x] Cache sweeper 

# 3.Deprecated
- [x] Drop setItoken and setItuid 
- [x] Drop `getXXX` in client

P.S.V2 still not available in stable.If you want to use v2, you can install `genshin-kit.js@next`
